### PR TITLE
DB create (Task 1)

### PR DESCRIPTION
**Pull request by Reillyminat**

### CODE REVIEW

**Review by mihail-saharilenko — CHANGES_REQUESTED** [review]
1. Why do you have one branch for several tasks? I can see here tasks for .Net and SQL as well.
2. Relation between Orders and Appliances tables is incorrect. You should be able to sell several products in one order, so relation Orders - Appliances should be of type many-to-many.
3. I suggest to rename Appliances to Products - product sounds more abstract then appliance, so you'll be able to sell anything in future.
4. Name of the ID field should reflect the name of the table. PK in AppliancesTypes table doesn't conform this rule, it's name is TypeId, which reflects the table name only partially and could confuse you in future if you'll have another table with some types.

**Comment by Reillyminat** [comment]
> 1. Why do you have one branch for several tasks? I can see here tasks for .Net and SQL as well.
> 2. Relation between Orders and Appliances tables is incorrect. You should be able to sell several products in one order, so relation Orders - Appliances should be of type many-to-many.
> 3. I suggest to rename Appliances to Products - product sounds more abstract then appliance, so you'll be able to sell anything in future.
> 4. Name of the ID field should reflect the name of the table. PK in AppliancesTypes table doesn't conform this rule, it's name is TypeId, which reflects the table name only partially and could confuse you in future if you'll have another table with some types.

Fixed all coments except 1. I created branch SQL based on master. Did you mean it has to be empty branch only with SQL tasks? Or is it problem with SQL.csproj in SQL folder? I haven`t found better way to organize folder in solution without creating a new project.

**Review by mihail-saharilenko — CHANGES_REQUESTED** [review]
image
image
You have 2 files related to SQL task, but there are 18 changed files in comparison to master in your branch. Usually, if it is PR for one task, you shouldn't have changes for another tasks there.

**Comment by Reillyminat** [comment]
> image
> image
> You have 2 files related to SQL task, but there are 18 changed files in comparison to master in your branch. Usually, if it is PR for one task, you shouldn't have changes for another tasks there.

I understood my fault. I had to do new branch based on master instead of last task branch. Next SQL task branch will be fine.

**Review by mihail-saharilenko — APPROVED** [review]

**Pull request merged**
